apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.taskID }}
  labels:
    app: {{ .Values.taskID }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.taskID }}
    spec:
      containers:
        - name: {{ .Values.taskID }}
          image: quay.io/fgimenez/lookout:{{ .SHA }}
          imagePullPolicy: Always
          env:
            - name: ORGANISATION
              value: {{ .Values.organisation }}
            - name: PROJECT
              value: {{ .Values.project }}
            - name: CHANNEL
              value: {{ .Values.channel }}
            - name: FIELD
              value: {{ .Values.field }}
          volumeMounts:
            - name: kubeconfig
              readOnly: false
              mountPath: /root/.kube
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig-{{ .Values.channel }}
