apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lookout-tacoshop-alpha
  labels:
    app: lookout-tacoshop-alpha
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lookout-tacoshop-alpha
    spec:
      serviceAccountName: lookout
      automountServiceAccountToken: true
      containers:
        - name: aaa
          image: quay.io/fgimenez/lookout:c0694a750ef8726200801af52a0c40d24b94dc29
          imagePullPolicy: IfNotPresent
          env:
            - name: TARGET_URL
              value: https://quay.io/cnr/api/v1/packages/fgimenez/tacoshop-chart/channels/alpha
            - name: FIELD
              value: current
